### ISSUE TITLE
How to publish redis client a message in any of the channels?

### ISSUE THREAD

**Issue by alexandercharlie** [dinostheo/redis_node_pbsb#1]
1. I cloned this project.
2. Configured everything and hit run. It's up and running on my browser.
3. Opened my **redis-cli** and added `sadd redis:channels channel1 channel2 channel3`.

Now I am not sure how to publish message in any of the channels? 
Any example from you will be quite helpful.

Thanks 👍

**Comment by dinostheo** [comment]
Hi, 

**DISCLAIMER**: This project is ancient. It was built for an old version of Node.js, perhaps 0.6 or 0.8 and it doesn't even have a package.json, but has the node_modules committed. So it would be better not to use this code 😄

For publishing in a message from your redis-cli you just have to execute the `publish` command with a message on one of the subscribed channels. e.g.

`publish channel1 "Hello world!"`

Finally, I understand that you are looking into building a realtime notifications systems using Node.js and redis. Perhaps, it might a good idea to create a new project where you can try using new code and techniques, as lots have changed in the world of javascript the last 5 years 😄 

Feel free to post me your repo if you decide to move forward with my advice and you need some reviewing or tips.

So to wrap it up, use the code to see how it runs, understand the concept and rebuild it better, way better, but please do not use the code of this repo in any system (production or development), not because I don't allow it, but because this code is 💩 
It's nice to remind me how I was trying to write Node.js and code in general 5 years ago, but that's all it can do 😃
